apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: postgres
  name: postgres
  namespace: test

spec:
  selector:
    matchLabels:
      app: postgres
  serviceName: postgres
  replicas: 1

  template:
    metadata:
      labels:
        app: postgres
      annotations:
        k8up.io/backupcommand: /bin/bash -c 'pg_dumpall -U ${POSTGRES_USER}'

    spec:
      containers:
        - name: postgres
          image: postgres:16.0-bookworm
          env:
            - name: POSTGRES_DB
              value: postgres
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: backup-test-creds
                  key: db-username
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: backup-test-creds
                  key: db-password
          ports:
            - containerPort: 5432
              name: postgres
