apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: mariadb
  name: mariadb
  namespace: test

spec:
  selector:
    matchLabels:
      app: mariadb
  serviceName: postgres
  replicas: 1

  template:
    metadata:
      labels:
        app: mariadb
      annotations:
        k8up.io/backupcommand: /bin/bash -c 'mysqldump -uroot -p"${MARIADB_ROOT_PASSWORD}" --all-databases'
    spec:
      containers:
        - image: mariadb:10.4
          name: mariadb
          env:
            - name: MARIADB_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: backup-test-creds
                  key: db-password
          ports:
            - containerPort: 3306
              name: mariadb
